### ISSUE TITLE
how to use in hosting

### ISSUE THREAD

**Issue by ntaloventi** [b374k/b374k#27]
Hi,

I'm using this tools, and work like charm on my local server, but how to achieve in hosting CGI/FastCGI 

TQ

**Comment by hiagohubert** [comment]
Put the b374k file in the folder that you run your php applications.

**Comment by ntaloventi** [comment]
dear hiagohubert,

thank for reply, sorry just read my mail, your notice thrown to spam, 
like I said "**works like charm on my local server**" but not in **shared hosting**...
maybe you have any other clue ?

**Comment by hiagohubert** [comment]
Hi ntaloventi, what is the version of PHP on the shared hosting? When you try to run b374k on shared hosting, it throws a error?
